[package]
name = "insim_core"
version = "1.0.0-alpha.1"
edition = "2021"
description = """
Core types and traits for the insim crate.
"""
repository = "https://github.com/theangryangel/insim"
rust-version = "1.66"

[lib]
bench = false
doctest = false

[dependencies]
bytes = "1"
encoding_rs = "0.8"
itertools = "0.12"
serde = { version = "1", features = ["derive"], optional = true }
once_cell = "1"
if_chain = "1.0.2"
binrw = "0.13.3"
