[package]
name = "insim_game_data"
version = "0.1.0"
edition = "2021"
description = """
Extended LFS Game Data, such as track and vehicle information
"""

[lib]
bench = false
doctest = false

[dependencies]
insim_core = { path = "../insim_core" }
