[package]
name = "insim"
version = "0.1.0"
authors = ["Karl Southern <karl@theangryangel.co.uk>"]
edition = "2018"

[lib]
bench = false

[dependencies]
futures = "0.3"
futures-core = "0.3"
bytes = "1"
tokio = { version = "1.11.0", features = ["full", "tracing"] }
tokio-util = { version = "0.6.8", features = ["full"] }
tokio-stream = { version = "0.1" }
deku = "0.12"
pin-project = "1"
itertools = "0.10"
encoding_rs = "0.8"
tracing = "0.1"
rand = "0.8"

[dev-dependencies]
# used in examples
tracing-subscriber = "0.2"
