[package]
name = "insim"
version = "0.3.0"
authors = ["Karl Southern <karl@theangryangel.co.uk>"]
edition = "2021"

[lib]
bench = false
doctest = false

[features]
serde = [
  "dep:serde",
  "insim_core/serde",
  "insim_game_data?/serde",
  "bitflags/serde",
]
game_data = ["dep:insim_game_data"]
pth = ["dep:insim_pth"]
smx = ["dep:insim_smx"]
# v9 = []
# latest = ["v9"]

[dependencies]
bytes = "1"
tokio = { version = "1.11.0", features = ["rt", "time", "net", "macros", "sync", "tracing"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"], optional = true }
bitflags = "2.4"
thiserror = "1"
async-trait = "0.1.68"
if_chain = "1"
insim_core = { path = "../insim_core" }
insim_game_data = { path = "../insim_game_data", optional = true }
insim_pth = { path = "../insim_pth", optional = true }
insim_smx = { path = "../insim_smx", optional = true }
tokio-tungstenite = "0.20.0"
futures-util = "0.3.28"
from_variants = "1.0.2"

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.2", features = ["derive"] }
tokio = { version = "1.11.0", features = ["full"] }
