[package]
name = "insim"
version = "0.3.0"
authors = ["Karl Southern <karl@theangryangel.co.uk>"]
edition = "2021"
rust-version = "1.66"

[lib]
bench = false
doctest = false

[features]
default = ["websocket"]
serde = [
  "dep:serde",
  "insim_core/serde",
  "bitflags/serde",
  "indexmap/serde",
]
pth = ["dep:insim_pth"]
smx = ["dep:insim_smx"]
websocket = ["dep:tokio-tungstenite"]
# TODO: feature flags for supported versions/packet defintions. How do we want to do this?
# v9 = []
# latest = ["v9"]

[dependencies]
bytes = "1"
tokio = { version = "1.11.0", features = ["rt", "time", "net", "macros", "sync", "tracing"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"], optional = true }
bitflags = "2.4"
thiserror = "1"
async-trait = "0.1.68"
if_chain = "1"
insim_core = { path = "../insim_core" }
insim_pth = { path = "../insim_pth", optional = true }
insim_smx = { path = "../insim_smx", optional = true }
tokio-tungstenite = { version = "0.21.0", optional = true }
futures-util = "0.3.28"
from_variants = "1.0.2"
indexmap = "2.1.0"

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.2", features = ["derive"] }
tokio = { version = "1.11.0", features = ["full"] }
