[package]
name = "low-level"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.2", features = ["derive"] }
if_chain = "1"
insim = { path = "../../insim" }
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
