[package]
name = "example-map"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
insim = { path = "../../" }
axum = { version = "0.3", features = ["headers"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tower-http = { version = "0.1", features = ["fs", "trace"] }
futures = "0.3"
flume = "0.10.9"
headers = "0.3"
serde_json = "1.0"
deku = "0.12"
