[package]
name = "simple-blocking"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.2", features = ["derive"] }
if_chain = "1"
insim = { path = "../../insim", default-features = false, features = ["blocking"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
